### ISSUE TITLE
[CLIENT-BUG] Clicking Shift in Game crashes Game

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#7] opened 2022-02-19 09:32 UTC
Clicking Shift in Game crashes Game

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Game'
2. Click on 'Shift'
3. See error

**Expected behaviour**
It to go to mod menu

**Desktop**
- OS: Windows 11
- Computer Hardware Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics
- Version Hash Evie Client Private Beta (4af4339)

**Comment by twisttaan** [comment] 2022-02-19 10:01
Hey, when did you click shift? In-game, or in a menu.

**Comment by tristancamejo** [comment] 2022-02-19 10:02
duplicate of https://github.com/EvieClient/EvieClient-Releases/issues/5

**Closed as completed by tristancamejo** 2022-02-19 10:02 UTC
Labels: client bug
