### ISSUE TITLE
[CLIENT-BUG] Minecraft Menu Fullscreen background too small 

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#4] opened 2022-02-19 09:17 UTC
**Describe the bug**
In the Menu if you go to Minecraft Fullscreen the Evie Client background is not big enough 

**To Reproduce**
1. Go to 'Minecraft'
2. Click on 'Fullscreen'
3. The Evie Background will be too small

**Expected behavior**
The Evie Background to be big enough

**Screenshots**
Added

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Computer Hardware Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics 
 - Version Hash EvieClient Private Beta (4af4339)

**Additional context**
![Screenshot (73)](https://user-images.githubusercontent.com/100020119/154794718-4eff53aa-24b5-4b15-8736-78881898f443.png)

**Comment by tristancamejo** [comment] 2022-02-19 10:03
duplicate of #2

**Closed as completed by tristancamejo** 2022-02-19 10:03 UTC
Labels: client bug
